### ISSUE TITLE
Problems when using @OrmLiteDao with different helpers

### ISSUE THREAD

**Issue by WonderCsabo** [androidannotations/androidannotations#1248]
If one uses the `@OrmliteDao` dao multiple times and uses different helpers for them, the [it will result in a `RuntimeException`](https://github.com/j256/ormlite-android/blob/28500b361072ab4c79f7448c32129495aaa279ef/src/main/java/com/j256/ormlite/android/apptools/OpenHelperManager.java#L155). This is because the `OpenHelperManager` was designed to manage on helper class at a time.

I do not know how we could validate this. Even if we manage to validate that all `OrmLiteDao` annotation in a class uses the same helper, it can be still problematic if the client uses it in another class, or calls `OpenHelperManager.getHelper` directly.
We should at least add a warning to the wiki and the javadoc.

@yDelouis WDYT?

**Comment by sinoohe** [comment]
we can use custom class instead of OpenHelperManager to open dao.  @OrmliteDao can be changed to use a custom class that holds multiple helpers within an array. am I right?
I have read OpenHelperManager class. It is very simple to change the functionality.

**Comment by WonderCsabo** [comment]
@sinoohe can you elaborate on what do you mean exactly?

**Comment by sinoohe** [comment]
in the init_ method (which is generated by androidannotation) instead of calling OpenHelperManager.getHelper , call  OpenHelperManager2.getHelper

define a custom OpenHelperManager2 class that holds helpers in an array. when you call OpenHelperManager.getHelper(context,class) it searches the entire array and finds a object with class matching the argument and return it, if object not found new Helper is initialized and is added to the array.


I don't know how to edit this project and I'm searching for it to custom it. 
sorry for my bad English, I hope I can tell you my idea.

**Comment by WonderCsabo** [comment]
@sinoohe i see. Unfortunetaly i do not think we want to support this in AndroidAnnotations. This is not a clean way, and also this is a special case, and we cannot support every aspect. It is better to let the programmer obtain the `Dao` by conventional coding.

**Comment by sinoohe** [comment]
Ok, I'm trying to fix it on my cloned version.
