### ISSUE TITLE
Add @RootFragment annotation for @EBean

### ISSUE THREAD

**Issue by LouisCAD** [androidannotations/androidannotations#1636]
Hi!

Currently, the only way to access the parent `Fragment` in an `@EBean` is by writing a setter in the bean manually, or by making a `@FragmentById`/`@FragmentByTag` public in the `@RootContext`annotated `Activity`. The code is not that beautiful, so why not create an `@RootFragment` annotation?

It would work the same way as `@RootContext`, excepted that it would not need to be re-injected if the Fragment instance is retained (see `setRetainInstance()` & `getRetainInstance()`) and the field is annotated with `NonConfigurationInstance` when config changes occurs (screen rotation, locale change, etc) as the Fragment itself (only it's View hierarchy) is not destroyed if retained.

Examples speak better than words, so here's how it would look like:

``` java
@EBean
public class MyRecyclerView extends RecyclerView.Adapter {

    @RootFragment
    MyEFragment mFragment;

    // I can now access the fragment, it's @InstanceState members,
    // and keep easily my adapter state, such as selected items
}
```

Below are the quotes to "help" implementation, from Gitter:

> - @WonderCsabo: the problem is that it is not trivial to implement
> - @LouisCAD: What would be the hard part(s)? Wouldn't it work by adding a setFragment_(MyEFragment fragment) call in onCreate() for all @EBeans in MyEFragment containing an @RootFragment field?
> - @WonderCsabo: Yeah, it is not too hard, that was an overstatement.

I'm on the way to learn how Annotation Processors work under the hood, so I hope I'll be able to add this myself (If I begin working on this, I'll post updates here), but if in the meantime, someone with the skills wants to add this new feature, I'd be very grateful (and I hope I would not be the only one).

**Comment by gauravsak** [comment]
@WonderCsabo I think this should be marked as an enhancement. Is that right?

**Comment by smaugho** [comment]
About this enhancement, we know that `@EBean` can have a the Singleton scope, in which case, I think it doesn't make sense that it'll be able to Inject a Fragment. 

So @WonderCsabo, @dodgex confirm me please if an implementation like this would work:

1. `@RootFragment` can only be injected in `@EBean` which aren't Singleton. 

I was thinking in using "setFragment_" on the Bean as proposed above, but that has a problem, when the "AfterInject" is called, the fragment will be no assigned yet (since it is called when the Bean `_getInstance(Context)` is called. A better solution would be then:

2. When injecting a bean with `@Bean`, on the "getInstance_" pass a second parameter (rootFragment_), so the injection would be like:

```java
  //If injected in fragment
  someBean = SomeBeanClass_.getInstance(getContext(), this);

  //If injected in another EBean:
  someBean = SomeBeanClass_.getInstance(getContext(), rootFragment_);

  //If injected in activity, or any other enhanced component
  someBean = SomeBeanClass_.getInstance(getContext(), null);

```

Please confirm me if you agree with this solution

**Comment by WonderCsabo** [comment]
I am fine with this solution, however i would create overloaded `getInstance()` methods, instead of passing `null`. That would also retain compatibility with previous AA versions.
