### ISSUE TITLE
Difference between androidannotations vs support-annotations

### ISSUE THREAD

**Issue by ahetawal-p** [androidannotations/androidannotations#1934]
Hello, 
I am trying to understand what is the difference between using the androidannotations library vs the support-annotations.

Using both in different projects I see this - 

![screen shot 2017-01-09 at 2 45 27 pm](https://cloud.githubusercontent.com/assets/8919529/21786870/0e2c3b00-d67b-11e6-9e1b-e03fc9b00410.png)

![screen shot 2017-01-09 at 2 45 00 pm](https://cloud.githubusercontent.com/assets/8919529/21786883/16c44ca8-d67b-11e6-9428-fcdfdbe3eddd.png)

I am looking to use the `@UiThread` annotation so that all my methods automatically run on UI thread.
But in support-annotations case I don't see the respective compile time code generated. 
Are these 2 different things ?

**Comment by dodgex** [comment]
Hello @ahetawal-p 

yes `support-annotations` and our `androidanntoations` are two completely diffrent projects and by no mean related.

`support-annotations` project is part of the android support libraries (as for example `support-v4`) and is developed by google. I'm not 100% sure about thier use but afaik it is primary for lint checks. Where I'm  sure is that they are not used for code generation like our annotations.

so if you want to use an annotation to ensure a method runs on the ui thread without dealing with handler and stuff by yourself you have to use our `@UiThread` annotation from the `org.androidannotations.annotations`  package instead of the one in `android.support.annotations`

**Comment by ahetawal-p** [comment]
Thanks @dodgex, makes sense now.
The only thing I am trying to use is the `@UiThread` code generation for my project. Is there any selective way I can use android-annotations to do that. When I try to annotate my activity with just `@UiThread` the compiler fails saying it needs the `@EActivity` tag also. I am already using butterknife and dagger in my project.

**Comment by dodgex** [comment]
If you want to use our `@UiThread`  annotation you have to use `@EActivity` (in case of activity) too.

**Comment by ahetawal-p** [comment]
I see, thanks @dodgex
