### ISSUE TITLE
@FragmentArg & @Extra doesn't work with Kotlin primitive types

### ISSUE THREAD

**Issue by n1n3b1t** [androidannotations/androidannotations#1944]
**AndroidAnnotations version**:
4.2.0
**Android compile SDK version**:
25
**Annotated code**:
```kotlin
@FragmentArg
var mode: Int = 0
```
Fails to build with kotlin 1-0-6

**Comment by WonderCsabo** [comment]
Please have a look at our [Kotlin example project](https://github.com/androidannotations/androidannotations/tree/develop/examples/kotlin), and add an `@Extra` field there, it works just fine. You have to use some modifiers though:
```kotlin
    @Extra
    protected lateinit var extra : String
```

**Comment by n1n3b1t** [comment]
It works with the string type, but doesn't compile with kotlin Int.

**Comment by WonderCsabo** [comment]
This is complicated. You cannot use `lateinit` for primitive types, so you must have to add a default value (as in your example):

```kotlin
    @Extra
    protected var extra: Int = 0
```

However this still does not compile, because the kotlin compiler reports that the property is `private`.
It seems it represents all not `lateinit` properties as `private` fields.

There is no way to inject primitive types currently, due to this limitation...

**Comment by TheMarketka** [comment]
Got around this using `@JvmField`.

**Comment by WonderCsabo** [comment]
Thanks for sharing, it is great there is a workaround for this.

**Comment by AntekM** [comment]
The same problem is with nullable fields (eg. String?). Fortunately exposing as field with @Jvm helps as well

**Comment by josinaldobarbosa** [comment]
```
@Extra
@JvmField
protected final var extra: Int = 0
```

[Wiki Kotlin-support](https://github.com/androidannotations/androidannotations/wiki/Kotlin-support)
