### ISSUE TITLE
Android Studio Plugin to solve AndroidAnnotations Debugging problems

### ISSUE THREAD

**Issue by smaugho** [androidannotations/androidannotations#1973]
Hi, 

One of the problems users affront with AndroidAnnotations, it is the viability to debug easily the code. More over, errors and warning generated from the framework are not distinguished from Java Error (in Eclipse, you get a beautiful message above the Annotations:

![image](https://cloud.githubusercontent.com/assets/6622086/23836444/b4a23664-0778-11e7-8224-38a015b5a3a3.png)

Sadly this is not what happens with Android Studio, you get a mess of compiling errors mixed with AA errors. 

Have you contemplated to build a plugin for Android Studio to solve this problems?

I don't have right now experience with the development of Plugins for IntelliJ platform, but it really worth it for this problem.

I'm also willing to try to integrate such plugin with Android Studio compiler (not sure if this will be possible), to debug Android Annotation generated code, even without going to the generated code (something like displaying part of this code in the normal editor when the debugger stops over the annotation, so breakpoints over annotations :) ).

This is not a request directly for the framework but over a new project completely linked to it.

With luck I could use it in a complex mechanism of java pseudo code analysis that I have in the framework I'm developing based in Android Annotation, [DecleX](https://github.com/smaugho/declex), where I'm parsing Java Code to generate Java Code in the Generated Class to make the code easier to write, and use fully injections capabilities of AndroidAnnotations:

```java
    @Click
    void btnLogin() {

        Dialog progressDialog = $ProgressDialog().message("Logging In...").dialog();

        $PutModel(login);
        if ($PutModel.Failed) {
            progressDialog.dismiss();
            $Toast("An error occurred");
        }

        progressDialog.dismiss();

        if (login.getSuccess() == 1) {
            $MainActivity();
            getActivity().finish();
        } else {
            $Toast(login.getMessage());
        }
    }
```

As you see I get rid completely of the ugly listeners, and the actions (those methods starting with "$") inject by them self all what they need to execute an action (they are basically @EBean).

I'm willing to start collecting information to really build this Plug-In, so your suggestions would be highly appreciated ;).

**Comment by WonderCsabo** [comment]
@smaugho the main problem is that if only one annotation fails, the project will spawn with hundreds of *cannot find symbol* errors. 

Yes, Eclipse was better on this, because errors were added directly to the source code, moreover due to incremental compilation, only the last changes compiled, and added errors, so not hundreds of errors came up. For now, the Android Gradle plugin will use full compilation when annotation processors are present, and it will even [not change in the future](https://blog.gradle.org/incremental-compiler-avoidance). This is because most of the processors was designed for full compilation only (but AndroidAnnotations was not, it always worked with incremental, and still does!).

I am pretty sure that lots of people demanded IntelliJ to show the errors directly in the source code in the editor. Instead of writing a plugin, we should find the relevant issue and whine in it. :)

Also, we already thought of changing our generation phase to avoid the hundreds of *cannot find symbol* errors. Now, if there is even one validation error, we skip processing and generating all classes. But this is not needed. We should only skip the generation of the class which is relevant. So if there are no validation errors in the class of the generating annotation, and any if its superclasses, we should generate the class. I thought i opened an issue for this, but i cannot find it now.

**Comment by dodgex** [comment]
I'd bet I have seen an issue for not skipping generation too... but maybe it was just us two writing in hangouts.

**Comment by smaugho** [comment]
Ok, I like the idea :-), of course, having a plugin to solve other issues (specially the Debugging problem, where to place the Breakpoint to Debug AndroidAnnotation Code!, that's a big issue for many programmers), I will study more about that topic... 

About generating the classes even after a validation failed, I really would like to implement it!, only getting read of that awful red list of errors would be a relief for many programmers, for sure... In the future maybe even a more coherent method can be done inside the Handlers, to separate the feature that failed from others... For instance, if the layout id passed to an @EActivity makes it failed (let's say, it is not a valid ID), it would be bad idea to stop completely the generation of the IntentBuilder, because if it is not generated, all the references to it would be shown as well in the error list (where the problem itself is a wrong layout ID)... 

So starting with generating all the other classes is really a Plus, but maybe it worth to think in a more general solution that includes as well the generation of internal components of the annotation.... Of course, that would demand grater changes.

**Comment by dodgex** [comment]
There was no extra issue for fixing the generation. It was just a part of another issue... see https://github.com/androidannotations/androidannotations/issues/1868#issuecomment-269757610

**Comment by dodgex** [comment]
@smaugho I'm not sure if it is worth the effort to build a plugin for debugging on annotations. not sure if that is even possible. imho one should still use the generated code to debug the generated code.

**Comment by smaugho** [comment]
I created a new issue for this  #1976 

About the plug-in I will gather much more information... 

Thank you very much for sharing your point of view  ;)..

**Comment by WonderCsabo** [comment]
@smaugho no problem! Actually i think it is always better to think IDE-independetly. I never liked solutions which depend on an IDE, or an IDE plugin. Of course, plugins could help, and i am not saying that the plugin you are mentioning is not helpful.
