### ISSUE TITLE
android annotations Error:(52, 42) error: cannot find symbol class Activity_

### ISSUE THREAD

**Issue by Millerscript** [androidannotations/androidannotations#1996]
i'm making a project with AA(Android Annotations), but, sometimes run and another times show this error.

Help!

Error code:

Information:Gradle tasks [:app:clean, :app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:assembleDebug]
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/co/com/barricade/model/push/FCMService.java
Error:(30, 25) error: cannot find symbol class MasterActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/co/com/barricade/ui/content/categorias/CategoriasBigListFragment.java
Error:(52, 42) error: cannot find symbol class SucursalActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/co/com/barricade/ui/MasterActivity.java
Error:(82, 40) error: cannot find symbol class OfertaActivity_
Error:(86, 42) error: cannot find symbol class SucursalActivity_
Error:(89, 38) error: cannot find symbol class PerfilActivity_
Error:(90, 38) error: cannot find symbol class PreferenciasCategoriasActivity_
Error:(91, 38) error: cannot find symbol class TerminiosYCondicionesActivity_
Error:(92, 48) error: cannot find symbol class HistorialCuponesActivity_
Error:(94, 53) error: cannot find symbol class NotificacionesActivity_
Error:(97, 31) error: cannot find symbol class LoginActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/co/com/barricade/ui/content/categorias/CategoriasSmallListFragment.java
Error:(53, 42) error: cannot find symbol class SucursalActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/co/com/barricade/ui/content/categorias/CategoriasMapFragment.java
Error:(54, 42) error: cannot find symbol class SucursalActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/co/com/barricade/ui/content/cercadeti/almacenes/CercaDeTiAlmacenesBigListFragment.java

Error:(70, 5) error: org.androidannotations.annotations.Background can only be used in a class annotated with @org.androidannotations.annotations.EApplication, @interface org.androidannotations.annotations.EActivity, @interface org.androidannotations.annotations.EViewGroup, @interface org.androidannotations.annotations.EView, @interface org.androidannotations.annotations.EBean, @interface org.androidannotations.annotations.EService, @interface org.androidannotations.annotations.EIntentService, @interface org.androidannotations.annotations.EReceiver, @interface org.androidannotations.annotations.EProvider, @interface org.androidannotations.annotations.EFragment.

**Comment by WonderCsabo** [comment]
As seen from the error message, you added the @Background annotation to a
class which is not enhanced. Please check the usage of @Background in your
code.

On Apr 21, 2017 23:21, "Miller Mosquera" <notifications@github.com> wrote:

i'm making a project with AA(Android Annotations), but, sometimes run and
another times show this error.

Help!

Error code:

Information:Gradle tasks [:app:clean, :app:generateDebugSources, :app:
generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:
prepareDebugUnitTestDependencies, :app:assembleDebug]
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/
co/com/barricade/model/push/FCMService.java
Error:(30, 25) error: cannot find symbol class MasterActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/
co/com/barricade/ui/content/categorias/CategoriasBigListFragment.java
Error:(52, 42) error: cannot find symbol class SucursalActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/
co/com/barricade/ui/MasterActivity.java
Error:(82, 40) error: cannot find symbol class OfertaActivity_
Error:(86, 42) error: cannot find symbol class SucursalActivity_
Error:(89, 38) error: cannot find symbol class PerfilActivity_
Error:(90, 38) error: cannot find symbol class
PreferenciasCategoriasActivity_
Error:(91, 38) error: cannot find symbol class
TerminiosYCondicionesActivity_
Error:(92, 48) error: cannot find symbol class HistorialCuponesActivity_
Error:(94, 53) error: cannot find symbol class NotificacionesActivity_
Error:(97, 31) error: cannot find symbol class LoginActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/
co/com/barricade/ui/content/categorias/CategoriasSmallListFragment.java
Error:(53, 42) error: cannot find symbol class SucursalActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/
co/com/barricade/ui/content/categorias/CategoriasMapFragment.java
Error:(54, 42) error: cannot find symbol class SucursalActivity_
/Users/MacDeveloper/Desktop/projectTest/app/src/main/java/
co/com/barricade/ui/content/cercadeti/almacenes/
CercaDeTiAlmacenesBigListFragment.java

Error:(70, 5) error: org.androidannotations.annotations.Background can only
be used in a class annotated with
@org.androidannotations.annotations.EApplication,
@interface <https://github.com/interface>
org.androidannotations.annotations.EActivity,
@interface <https://github.com/interface>
org.androidannotations.annotations.EViewGroup,
@interface <https://github.com/interface>
org.androidannotations.annotations.EView,
@interface <https://github.com/interface>
org.androidannotations.annotations.EBean,
@interface <https://github.com/interface>
org.androidannotations.annotations.EService,
@interface <https://github.com/interface>
org.androidannotations.annotations.EIntentService,
@interface <https://github.com/interface>
org.androidannotations.annotations.EReceiver,
@interface <https://github.com/interface>
org.androidannotations.annotations.EProvider,
@interface <https://github.com/interface> org.androidannotations.
annotations.EFragment.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/androidannotations/androidannotations/issues/1996>, or mute
the thread

**Comment by Millerscript** [comment]
Hi @WonderCsabo thank you so much, worked!
