### ISSUE TITLE
Is it possible to choose the Content-Type for file upload?

### ISSUE THREAD

**Issue by Aqua-Ye** [androidannotations/androidannotations#1998]
Is it possible to change/override the "Content-Type" for a file upload?
Currently, I see "Content-Type: application/octet-stream"

**Comment by WonderCsabo** [comment]
You can easily overwrite headers with the `@Header` annotation, or with an interceptor. Please see the wiki, everything is documented.

**Comment by Aqua-Ye** [comment]
I am already using for the call: 

```
@Header(name = HttpHeaders.CONTENT_TYPE, value = MediaType.MULTIPART_FORM_DATA_VALUE)
```

But the file I pass in @Body with `new FileSystemResource(file)` is detected as `application/octet-stream`.

With an interceptor, the data has already been detected in the `byte[] data` field.

Any other solution?

**Comment by WonderCsabo** [comment]
What do you want to achieve exactly?

**Comment by Aqua-Ye** [comment]
Currently, in the multipart data, I have (printed from the interceptor): 

```
--WHwMDrcDRI_EDueSlKXqnYBA2NnKDh
Content-Disposition: form-data; name="video"; filename="video-encoded.mp4"
Content-Type: application/octet-stream
Content-Length: 530136
BINARY DATA
--WHwMDrcDRI_EDueSlKXqnYBA2NnKDh
Content-Disposition: form-data; name="duration"
Content-Type: text/plain;charset=ISO-8859-1
Content-Length: 1
3
--WHwMDrcDRI_EDueSlKXqnYBA2NnKDh--
```

I would like to send: 

```
--WHwMDrcDRI_EDueSlKXqnYBA2NnKDh
Content-Disposition: form-data; name="video"; filename="video-encoded.mp4"
Content-Type: video/mp4
Content-Length: 530136
BINARY DATA
--WHwMDrcDRI_EDueSlKXqnYBA2NnKDh
Content-Disposition: form-data; name="duration"
Content-Type: text/plain;charset=ISO-8859-1
Content-Length: 1
3
--WHwMDrcDRI_EDueSlKXqnYBA2NnKDh--
```

**Comment by WonderCsabo** [comment]
OK, i see, you want to change the headers inside the body. That is not the HTTP headers actually what you want to change, that should be still `multipart/form-data`.

The problem is that the Spring resource converter [uses](https://github.com/spring-projects/spring-android/blob/master/spring-android-rest-template/src/main/java/org/springframework/http/converter/ResourceHttpMessageConverter.java#L62) `application/octet-stream` by default.

You can have two options to fix this:

1. Subclass `ResourceHttpMessageConverter` and overwrite its `getDefaultContentType()` to return the content types as your logic, and register your converter instead of the default `ResourceHttpMessageConverter` in `RestTemplate`.

2. Add the headers individually when setting the part parameters:

```java
@Post("http://your.api/multipart-post")
void multipartPost(@Part HttpEntity<FileSystemResource> resource);

HttpHeaders httpHeaders = new HttpHeaders();
httpHeaders.setContentType(MediaType.parseMediaType("video/mp4"));
HttpEntity<FileSystemResource> entity = new HttpEntity<FileSystemResource>(new FileSystemResource("path_to_your_video.mp4"), httpHeaders);
service.multipartPost(entity)
```
