### ISSUE TITLE
Compile too slowly

### ISSUE THREAD

**Issue by cxc2014** [androidannotations/androidannotations#2052]
Number of files generated by AndroidAnnotations: 214

16:27:11.374 [Task worker Thread 3] INFO  o.a.i.p.TimeStats:81 - Time measurements: [Whole Processing = 14851 ms], [Generate Sources = 14205 ms], [Process Annotations = 268 ms], [Validate Annotations = 235 ms], [Extract Annotations = 115 ms], [Find R Classes = 15 ms], [Extract Manifest = 10 ms]

Modify 1 line in 1 file, compile need 28.317 secs,  AA is generated 214 file,  is it possible to make compile fast?

MacBook Pro (Retina, 15-inch, Mid 2014) 
( 2.5 GHz Intel Core i7)

[aa.log](https://github.com/androidannotations/androidannotations/files/1381444/aa.log)

**Comment by smaugho** [comment]
If Gradle has an incremental compilation option similar to ANT, then this would be a gradle option. 

There's a workaround which could be done, I was trying to implement it in an AndroidAnnotation derived project. 

Basically, AndroidAnnotations could detect if a Java class file changed or not, and based in this, validate and process this class annotations, or exclude them from the validation/processing phase. 

This introduced a problem, and it is that the enhanced class is not generated in the compilation run (of course). To solve this issue, a cache of the first compilation should be done, and the class should be copied to the Java Output folder. 

There's another problem which appears with this, and it is that Java doesn't detect the generated classes copied to the output folder from the Cache. This generates a compilation error (class not found). For this there's a second workaround. The mentioned Cache can be a .jar, and this .jar can be provided to java (via gradle "provided" method in the dependencies). This doesn't conflict with the classes if they are re-generated. 

With this workaround I did a method to make AndroidAnnotation to compile faster, but since it was created in a derived library, this cannot be integrated automatically into AndroidAnnotations.. It would be nice to see if in the future a similar method can be integrated into AA anyway, this will speed up a lot the framework.

**Comment by WonderCsabo** [comment]
AndroidAnnotations fully supports incremental compilation. It was always designed to support it.

However, [Gradle will always do a full compile if annotation processors are present](https://blog.gradle.org/incremental-compiler-avoidance), because most of the processors require a full build (shame for them :) ). AFAIK, the Android tool / Gradle team are working to resolve this issue.

What you can do now is breaking your project into separate Gradle modules, then you will only compile the subset of classes which are in the modified module during incremental build.
