### ISSUE TITLE
library annotationProcessorOptions is not working

### ISSUE THREAD

**Issue by doerschner** [androidannotations/androidannotations#2053]
**AndroidAnnotations version**: 4.3.1
**Android compile SDK version**: 26
**Gradle version**: 2.3.3

I added the javaCompileOptions-block to my module like this:
```
javaCompileOptions {
    annotationProcessorOptions {
        arguments = ["logLevel"          : "TRACE",
                     "logAppenderConsole": "true",
                     "library"           : "true"]
    }
}
```
I added AA like this:
```
def AAVersion = '4.3.1'
dependencies {
    annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
    compile "org.androidannotations:androidannotations-api:$AAVersion"
}
```

But if I try to add Ids to the code it still says this static-not-final-variable message.
Did I miss something? I know there are different possibilities, for example the butterknife-R2 method, but I still would like to use this one, because it seems to be the cleanest one (at least at the moment)

**Comment by WonderCsabo** [comment]
Unfortunately we cannot use the R.xx.xx fields in libraries as annotation values, because they are not final in library projects, but the Java specification requires it. You can work around this in two ways:

1. using [`resName`](https://github.com/androidannotations/androidannotations/wiki/Library-projects#referencing-ids-by-name) in annotations, using String as a value, like: `@EActivity(resName = "activity_main".
2. Using the ButterKnife Gradle plugin to generate the final `R2` class and use that, as you mentioned.

There is no other way.
