### ISSUE TITLE
startForResult from @EFragment documentation confusion

### ISSUE THREAD

**Issue by marmor7** [androidannotations/androidannotations#2182]
Had issues with getting my `@OnActivityResult` called after calling `startForResult` from my Fragment, after short debugging, I realized that using `getContext()` when creating the IntentBuilder will cause the `startForResult` to fail, instead I had to use `this`.

I didn't see anything about that in the documentation, and didn't realize there's even a constructor that accepts fragments to `IntentBuilder`, I think that's something that should be added under `@EFragment` docs.

Within `@EFragment`s:
```
MyActivity_.intent(getContext()).startForResult(RC_VALUE); // will silently fail
MyActivity_.intent(this).startForResult(RC_VALUE); // will work
```

**Comment by dodgex** [comment]
Not sure about `getContext()` but if you call `getActivity()` the `@OnActivityResult` annotated method has to be in the Activity. with `getFragment()` the annotated method has to be in the Fragment.

according to [this SO Question](https://stackoverflow.com/questions/32227146/what-is-different-between-getcontext-and-getactivity-from-fragment-in-support-li/) `getContext()` returns the context wich might be a activity, but also might not.

I'd suggest to use it with the `getFragment()` if you want to handle the result in the fragment or `getActivity()` if you want to handle the result in the activity.

**Comment by WonderCsabo** [comment]
I agree with @dodgex . This is standard Android behavior, nothing special with AA here.

In plain Android, from a `Fragment`:

`this.startActivity()` -> `onActivityResult()` will called on `this` `Fragment`
`getContext().startActivity()` -> `onActivityResult()` will called on the `Activity` if that is under `getContext()`

This is pretty straithforward, since in the second case, the system actually do not know that you called `startActivity()` from the `Fragment` at all.
