### ISSUE TITLE
Support Gradle incremental annotation processing

### ISSUE THREAD

**Issue by WonderCsabo** [androidannotations/androidannotations#2193]
https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing

**Comment by smaugho** [comment]
@WonderCsabo just checking the code in the `PrefHandler` I found this:

```java
Set<? extends Element> sharedPrefElements = getEnvironment().getValidatedElements().getRootAnnotatedElements(SharedPref.class.getName());
for (Element sharedPrefElement : sharedPrefElements) {
	GeneratedClassHolder sharedPrefHolder = getEnvironment().getGeneratedClassHolder(sharedPrefElement);
	String sharedPrefName = sharedPrefHolder.getGeneratedClass().name();

	if (elementTypeName.equals(sharedPrefName)) {
		prefClass = sharedPrefHolder.getGeneratedClass();
		break;
	}
}
```

This code assumes that all the `@SharedPref` annotated classes are being processed in the environment. This would be no that different that what we were talking on #1520. This should break with incremental compilations, since there is no guarantee that the `@SharedPref` annotated classes would be processed when using incremental compilation.

**Comment by WonderCsabo** [comment]
We have to check it. The docs says we can access the elements in the annotated elements AST, but i am not sure we will reach it trought the validated elements, maybe we have to do otherwise.

**Comment by IgorB10** [comment]
Hi! Was wondering if you're planning to add support this?

**Comment by WonderCsabo** [comment]
We are planning, yes. ;) Contributions are very much welcome.
