### ISSUE TITLE
Error:java, java.lang.NoClassDefFoundError: org/androidannotations/annotations/EActivity 

### ISSUE THREAD

**Issue by fyname** [androidannotations/androidannotations#948]
used androidannotations 3.0.1 

```
    <dependency>
        <groupId>org.androidannotations</groupId>
        <artifactId>androidannotations</artifactId>
        <scope>provided</scope>
    </dependency>
```

config:
      E:\opt\m2\repository\org\androidannotations\androidannotations\3.0.1\androidannotations-3.0.1.jar

compile show:

Error:java: 错误：构造处理程序对象 java.lang.NoClassDefFoundError: org/androidannotations/annotations/EActivity 时抛出异常

**Comment by tuanphambiglab** [comment]
Hi man,

I followed exactly steps as guide https://github.com/excilys/androidannotations/wiki/IntelliJIDEA.
But still have error Error:java: java.lang.NoClassDefFoundError: org/androidannotations/annotations/EActivity, when make application.

Now app is using newest androidannotations(version 3.3.1).

Could you help me?
Thanks.

**Comment by WonderCsabo** [comment]
I think the problem is you are using the [processor jar without the dependencies](http://search.maven.org/remotecontent?filepath=org/androidannotations/androidannotations/3.3.1/androidannotations-3.3.1.jar). You should use the jar found in the [bundle](http://search.maven.org/remotecontent?filepath=org/androidannotations/androidannotations-bundle/3.3.1/androidannotations-bundle-3.3.1.zip).

BTW, i strongly suggest to use a build system, like Gradle, which is much more convenient, has lot of advantages and the official way to build Android apps.

**Comment by tuanphambiglab** [comment]
Thanks man. It worked now, because i'm using Gradle downloaded file library to build as normal version.
Using [download version](https://github.com/excilys/androidannotations/wiki/Download) to build, it worked.
